version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=faq_p.settings
      - PYTHONPATH=/app
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

  test:
    build: .
    command: pytest -v --cov=faq_app
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=faq_p.settings
      - PYTHONPATH=/app
    depends_on:
      - redis

volumes:
  redis_data: